import Store from 'electron-store'
import { DEFAULT_PROMPT_PREFIX } from './constants'

export interface Settings {
  freenewsApiKey: string
  freenewsBaseUrl: string
  aiEnabled: boolean
  aiProviderType: 'openai' | 'anthropic'
  aiBaseUrl: string
  aiApiKey: string
  aiModel: string
  aiDecisionMode: 'threshold_only' | 'hybrid' | 'llm_only'
  aiPrescreenEnabled: boolean
  aiPrescreenThreshold: number
  checkInterval: number
  monitorFetchLimit: number
  alertCooldownMinutes: number
  autoBriefEnabled: boolean
  autoBriefIntervalHours: number
  notifications: boolean
  sound: boolean
  autoStart: boolean
  // Global AI role prompt prefix (user-editable, prepended to every analysis request)
  // 全局 AI 角色前缀（用户可编辑，拼接在每次分析请求的最前面）
  aiPromptPrefix: string
  timezone: string
  language: 'zh' | 'en'
  theme: 'dark' | 'light'
  customPresets: Array<{ label: string; value: string }>
  /** Tier-1: trigger alert when importanceScore >= this value (1~10, default 7) */
  importanceThreshold: number
  /** Tier-1: trigger alert when sentimentScore <= this value (0~1, default 0.25) */
  negativeSentimentThreshold: number
}

export interface Keyword {
  id: string
  name: string
  groupId?: string
  groupName?: string
  // Kept for backward compatibility; current monitoring searches all languages
  // 兼容旧数据保留，当前监控固定搜索全部语言
  regions: string[]
  alertThreshold: number
  /** Per-topic importance threshold override; null = use global Settings.importanceThreshold */
  topicImportanceThreshold: number | null
  /** Per-topic negative sentiment threshold override; null = use global Settings.negativeSentimentThreshold */
  topicNegativeSentimentThreshold: number | null
  status: 'normal' | 'warning' | 'alert' | 'paused'
  todayCount: number
  todayCountDate?: string
  lastChecked: string | null
  latestArticleTitle: string | null
  latestArticleTitleEn: string | null
  latestArticleUrl: string | null
  latestArticleSource: string | null
  sentimentHistory: number[]
  seenArticleIds: number[]
  // Per-keyword custom prompt override (falls back to global prefix when empty)
  // 覆盖全局前缀的自定义 prompt（为空则使用全局）
  customPrompt: string
}

export interface AlertRelatedArticle {
  id: number | null
  title: string
  titleZh: string | null
  titleEn: string | null
  url: string
  sourceName: string
  publishedAt: string | null
  summary: string | null
  summaryZh: string | null
  summaryEn: string | null
  sentimentScore: number | null
  sentimentLabel: string | null
  /** Backend importance score 1~10; null if backend hasn't analyzed yet */
  /** 后端重要性评分 1~10，后端尚未分析时为 null */
  importanceScore: number | null
  keywordsZh: string[]
  keywordsEn: string[]
  _raw?: Record<string, unknown>
}

export interface Alert {
  id: string
  keywordId: string
  keywordName: string
  severity: 'high' | 'medium' | 'low'
  reason: string
  reasonEn: string | null
  articleTitle: string
  articleTitleZh: string | null
  articleTitleEn: string | null
  articleUrl: string
  articleSource: string | null
  articlePublishedAt: string | null
  articleSummary: string | null
  articleSummaryZh: string | null
  articleSummaryEn: string | null
  queryExpression: string | null
  sentimentScore: number | null
  sentimentLabel: string | null
  /** Backend importance score 1~10 for the triggering article */
  /** 触发告警文章的后端重要性评分 1~10 */
  articleImportance: number | null
  aiReasoning: string | null
  aiImpact: number | null
  aiImpactDirection: 'negative' | 'neutral' | 'positive' | null
  aiUrgency: 'low' | 'medium' | 'high' | null
  aiRelevance: number | null
  relatedArticles: AlertRelatedArticle[]
  timestamp: string
  read: boolean
}

export interface Brief {
  id: string
  keywords: string[]
  topicIds?: string[]
  topics?: string[]
  dateRange?: string
  autoGenerated?: boolean
  generatedAt: string
  content: string
}

export interface TopicRunArticle {
  id: number
  title: string
  titleZh: string | null
  titleEn: string | null
  url: string
  sourceCode: string | null
  sourceName: string
  language: string | null
  publishedAt: string | null
  summary: string | null
  summaryZh: string | null
  summaryEn: string | null
  sentimentScore: number | null
  sentimentLabel: string | null
  /** Backend importance score 1~10; null if backend hasn't analyzed yet */
  /** 后端重要性评分 1~10，后端尚未分析时为 null */
  importanceScore: number | null
  keywordsZh: string[]
  keywordsEn: string[]
  categories: string[]
  aiReasoning: string | null
  aiImpact: number | null
  aiImpactDirection: 'negative' | 'neutral' | 'positive' | null
  aiUrgency: 'low' | 'medium' | 'high' | null
  aiRelevance: number | null
  triggerAlert: boolean
  /** Raw API response — future-proof against new fields */
  /** 原始 API 返回，未来有新字段不用改代码 */
  _raw?: Record<string, unknown>
}

export interface TopicRunRecord {
  id: string
  groupId: string
  groupName: string
  checkedAt: string
  queryExpression: string
  articleCount: number
  newArticleCount: number
  aiEvaluatedCount?: number
  sampledArticleCount?: number
  status: Keyword['status']
  matchedRegions: string[]
  triggered: boolean
  alertId: string | null
  latestArticleTitle: string | null
  latestArticleTitleEn: string | null
  latestArticleUrl: string | null
  latestArticleSource: string | null
  reason: string | null
  recentArticles?: TopicRunArticle[]
}

interface StoreSchema {
  storeVersion: number
  settings: Settings
  // Legacy payload keys (pre-SQLite) kept optional for one-time cleanup.
  keywords?: Keyword[]
  alerts?: Alert[]
  briefs?: Brief[]
  topicRuns?: TopicRunRecord[]
  briefRuntime?: {
    lastAutoBriefAt: string | null
  }
}

// Current data version (settings only)
/** 当前数据版本（settings only） */
const CURRENT_STORE_VERSION = 3

export const store = new Store<StoreSchema>({
  defaults: {
    storeVersion: CURRENT_STORE_VERSION,
    settings: {
      freenewsApiKey: '',
      freenewsBaseUrl: 'https://freenews.site',
      aiEnabled: false,
      aiProviderType: 'openai',
      aiBaseUrl: 'https://api.openai.com/v1',
      aiApiKey: '',
      aiModel: 'gpt-4o-mini',
      aiDecisionMode: 'hybrid',
      aiPrescreenEnabled: false,
      aiPrescreenThreshold: 0.3,
      checkInterval: 5,
      monitorFetchLimit: 20,
      alertCooldownMinutes: 30,
      autoBriefEnabled: false,
      autoBriefIntervalHours: 12,
      notifications: true,
      sound: false,
      autoStart: true,
      aiPromptPrefix: DEFAULT_PROMPT_PREFIX,
      timezone: 'Asia/Shanghai',
      language: 'zh',
      theme: 'dark',
      customPresets: [],
      importanceThreshold: 7,
      negativeSentimentThreshold: 0.25
    }
  }
})

// ─── Data migration: maintain settings version number only ───
// ─── 数据迁移：仅维护 settings 版本号 ─────────────────────────
;(function migrateStore() {
  const savedVersion = (store.get('storeVersion') as number) ?? 0
  const hasLegacyPayload =
    store.has('keywords') ||
    store.has('alerts') ||
    store.has('briefs') ||
    store.has('topicRuns') ||
    store.has('briefRuntime')

  if (hasLegacyPayload) {
    store.delete('keywords')
    store.delete('alerts')
    store.delete('briefs')
    store.delete('topicRuns')
    store.delete('briefRuntime')
  }

  if (savedVersion >= CURRENT_STORE_VERSION && !hasLegacyPayload) return

  store.set('storeVersion', CURRENT_STORE_VERSION)
  if (process.env.NODE_ENV !== 'production') {
    console.log(`[Store] Settings schema version set to v${CURRENT_STORE_VERSION}`)
  }
})()
