import { create } from 'zustand'

export interface Settings {
  freenewsApiKey: string
  freenewsBaseUrl: string
  aiEnabled: boolean
  aiProviderType: 'openai' | 'anthropic'
  aiBaseUrl: string
  aiApiKey: string
  aiModel: string
  aiDecisionMode: 'threshold_only' | 'hybrid' | 'llm_only'
  aiPrescreenEnabled: boolean
  aiPrescreenThreshold: number
  checkInterval: number
  monitorFetchLimit: number
  alertCooldownMinutes: number
  autoBriefEnabled: boolean
  autoBriefIntervalHours: number
  notifications: boolean
  sound: boolean
  autoStart: boolean
  aiPromptPrefix: string
  timezone: string
  language: 'zh' | 'en'
  theme: 'dark' | 'light'
  customPresets: Array<{ label: string; value: string }>
  /** Tier-1: trigger alert when importanceScore >= this value (1~10, default 7) */
  importanceThreshold: number
  /** Tier-1: trigger alert when sentimentScore <= this value (0~1, default 0.25) */
  negativeSentimentThreshold: number
}

export interface Keyword {
  id: string
  name: string
  groupId?: string
  groupName?: string
  // 兼容旧数据保留，当前监控固定搜索全部语言
  regions: string[]
  alertThreshold: number
  /** Per-topic importance threshold override; null = use global Settings.importanceThreshold */
  topicImportanceThreshold: number | null
  /** Per-topic negative sentiment threshold override; null = use global Settings.negativeSentimentThreshold */
  topicNegativeSentimentThreshold: number | null
  status: 'normal' | 'warning' | 'alert' | 'paused'
  todayCount: number
  todayCountDate?: string
  lastChecked: string | null
  latestArticleTitle: string | null
  latestArticleTitleEn: string | null
  latestArticleUrl: string | null
  latestArticleSource: string | null
  sentimentHistory: number[]
  seenArticleIds: number[]
  customPrompt: string
}

export interface AlertRelatedArticle {
  id: number | null
  title: string
  titleZh: string | null
  titleEn: string | null
  url: string
  sourceName: string
  publishedAt: string | null
  summary: string | null
  summaryZh: string | null
  summaryEn: string | null
  sentimentScore: number | null
  sentimentLabel: string | null
  /** Backend importance score 1~10; null if backend hasn't analyzed yet */
  /** 后端重要性评分 1~10，后端尚未分析时为 null */
  importanceScore: number | null
  keywordsZh: string[]
  keywordsEn: string[]
  _raw?: Record<string, unknown>
}

export interface Alert {
  id: string
  keywordId: string
  keywordName: string
  severity: 'high' | 'medium' | 'low'
  reason: string
  reasonEn: string | null
  articleTitle: string
  articleTitleZh: string | null
  articleTitleEn: string | null
  articleUrl: string
  articleSource: string | null
  articlePublishedAt: string | null
  articleSummary: string | null
  articleSummaryZh: string | null
  articleSummaryEn: string | null
  queryExpression: string | null
  sentimentScore: number | null
  sentimentLabel: string | null
  /** Backend importance score 1~10 for the triggering article */
  /** 触发告警文章的后端重要性评分 1~10 */
  articleImportance: number | null
  aiReasoning: string | null
  aiImpact: number | null
  aiImpactDirection: 'negative' | 'neutral' | 'positive' | null
  aiUrgency: 'low' | 'medium' | 'high' | null
  aiRelevance: number | null
  relatedArticles: AlertRelatedArticle[]
  timestamp: string
  read: boolean
}

export interface Brief {
  id: string
  keywords: string[]
  topicIds?: string[]
  topics?: string[]
  dateRange?: string
  autoGenerated?: boolean
  generatedAt: string
  content: string
}

export interface TopicRunArticle {
  id: number
  title: string
  titleZh: string | null
  titleEn: string | null
  url: string
  sourceCode: string | null
  sourceName: string
  language: string | null
  publishedAt: string | null
  summary: string | null
  summaryZh: string | null
  summaryEn: string | null
  sentimentScore: number | null
  sentimentLabel: string | null
  /** Backend importance score 1~10; null if backend hasn't analyzed yet */
  /** 后端重要性评分 1~10，后端尚未分析时为 null */
  importanceScore: number | null
  keywordsZh: string[]
  keywordsEn: string[]
  categories: string[]
  aiReasoning: string | null
  aiImpact: number | null
  aiImpactDirection: 'negative' | 'neutral' | 'positive' | null
  aiUrgency: 'low' | 'medium' | 'high' | null
  aiRelevance: number | null
  triggerAlert: boolean
  _raw?: Record<string, unknown>
}

export interface TopicRunRecord {
  id: string
  groupId: string
  groupName: string
  checkedAt: string
  queryExpression: string
  articleCount: number
  newArticleCount: number
  aiEvaluatedCount?: number
  sampledArticleCount?: number
  status: Keyword['status']
  matchedRegions: string[]
  triggered: boolean
  alertId: string | null
  latestArticleTitle: string | null
  latestArticleTitleEn: string | null
  latestArticleUrl: string | null
  latestArticleSource: string | null
  reason: string | null
  recentArticles?: TopicRunArticle[]
}

export interface Stats {
  totalKeywords: number
  activeKeywords: number
  todayNews: number
  todayAlerts: number
  totalBriefs: number
  unreadAlerts: number
}

export interface MonitorStatus {
  running: boolean
  status: 'running' | 'paused' | 'idle' | 'missing_api_key'
  message: string
  autoStart: boolean
  lastCycleAt: string | null
}

interface AppState {
  currentPage: string
  settings: Settings
  keywords: Keyword[]
  alerts: Alert[]
  briefs: Brief[]
  topicRuns: TopicRunRecord[]
  stats: Stats
  monitorStatus: MonitorStatus
  alertDetailId: string | null
  loading: boolean

  setPage: (page: string) => void
  setSettings: (s: Settings) => void
  setKeywords: (kws: Keyword[]) => void
  setAlerts: (alerts: Alert[]) => void
  setBriefs: (briefs: Brief[]) => void
  setTopicRuns: (runs: TopicRunRecord[]) => void
  setStats: (stats: Stats) => void
  setMonitorStatus: (status: MonitorStatus) => void
  setAlertDetailId: (id: string | null) => void
  setLoading: (v: boolean) => void
  applyKeywordUpdate: (kw: Keyword) => void
  addAlert: (alert: Alert) => void
  updateAlertReadState: (id: string, read: boolean) => void
  markAllAlertsRead: () => void
  addTopicRun: (run: TopicRunRecord) => void
  addBrief: (brief: Brief) => void
}

function getTodayKey() {
  const now = new Date()
  const year = now.getFullYear()
  const month = String(now.getMonth() + 1).padStart(2, '0')
  const day = String(now.getDate()).padStart(2, '0')
  return `${year}-${month}-${day}`
}

function computeStats(keywords: Keyword[], alerts: Alert[], briefs: Brief[]): Stats {
  const today = new Date().toDateString()
  const todayKey = getTodayKey()

  return {
    totalKeywords: keywords.length,
    activeKeywords: keywords.filter((k) => k.status !== 'paused').length,
    todayNews: keywords.reduce(
      (sum, k) => sum + (k.todayCountDate === todayKey ? k.todayCount : 0),
      0
    ),
    todayAlerts: alerts.filter((a) => new Date(a.timestamp).toDateString() === today).length,
    totalBriefs: briefs.length,
    unreadAlerts: alerts.filter((a) => !a.read).length
  }
}

const DEFAULT_PROMPT_PREFIX = `你是一名长期从事地缘政治与国家安全分析的情报人员，拥有丰富的开源情报（OSINT）分析经验。你的任务不是简单理解新闻，而是从公开信息中识别潜在风险信号与战略意图。

你的核心目标：从新闻中提取"对国家安全、资本市场、区域稳定产生实质影响的信号"，并忽略日常信息噪音。

🔴 高风险信号（必须100%捕捉）
- 国家间军事行动、冲突升级、军演异常
- 制裁、贸易战升级、外交关系破裂
- 政权不稳定（政变、抗议升级、选举争议）
- 核心资源（能源、粮食、关键矿产）供应受影响
- 金融系统风险（主权债务危机、资本管制）
- 科技封锁（芯片禁令、出口限制）
- 重大恐袭或安全事件

🟠 中风险信号（需要关注趋势）
- 政策转向（监管收紧/放松）
- 国际联盟变化（结盟、对抗）
- 关键人物发言（总统、央行、军方）
- 产业链转移、供应链重构
- 经济数据异常（通胀、失业、外汇）

⚪ 噪音（直接忽略）
- 普通经济分析、日常外交表态（无实质变化）
- 预测性文章（没有事件支撑）、重复报道

⚠️ 判断原则：宁可漏掉一般性新闻，也必须捕捉所有"冲突升级"或"系统性风险"信号。优先关注"变化"而非"状态"——如果新闻只是描述现状则低价值，如果暗示趋势改变则高价值。reasoning字段必须说明"这条信息改变了什么"。`

export const useStore = create<AppState>((set) => ({
  currentPage: 'dashboard',
  settings: {
    freenewsApiKey: '',
    freenewsBaseUrl: 'https://freenews.site',
    aiEnabled: false,
    aiProviderType: 'openai',
    aiBaseUrl: 'https://api.openai.com/v1',
    aiApiKey: '',
    aiModel: 'gpt-4o-mini',
    aiDecisionMode: 'hybrid',
    aiPrescreenEnabled: false,
    aiPrescreenThreshold: 0.3,
    checkInterval: 5,
    monitorFetchLimit: 50,
    alertCooldownMinutes: 5,
    autoBriefEnabled: false,
    autoBriefIntervalHours: 12,
    notifications: true,
    sound: false,
    autoStart: false,
    aiPromptPrefix: DEFAULT_PROMPT_PREFIX,
    timezone: 'Asia/Shanghai',
    language: 'zh',
    theme: 'dark',
    customPresets: [],
    importanceThreshold: 5,
    negativeSentimentThreshold: 0.5
  },
  keywords: [],
  alerts: [],
  briefs: [],
  topicRuns: [],
  stats: { totalKeywords: 0, activeKeywords: 0, todayNews: 0, todayAlerts: 0, totalBriefs: 0, unreadAlerts: 0 },
  monitorStatus: {
    running: false,
    status: 'idle',
    message: '监控未启动',
    autoStart: true,
    lastCycleAt: null
  },
  alertDetailId: null,
  loading: false,

  setPage: (page) => set({ currentPage: page }),
  setSettings: (settings) => set({ settings }),
  setKeywords: (keywords) =>
    set((state) => ({
      keywords,
      stats: computeStats(keywords, state.alerts, state.briefs)
    })),
  setAlerts: (alerts) =>
    set((state) => ({
      alerts,
      stats: computeStats(state.keywords, alerts, state.briefs)
    })),
  setBriefs: (briefs) =>
    set((state) => ({
      briefs,
      stats: computeStats(state.keywords, state.alerts, briefs)
    })),
  setTopicRuns: (topicRuns) => set({ topicRuns }),
  setStats: (stats) => set({ stats }),
  setMonitorStatus: (monitorStatus) => set({ monitorStatus }),
  setAlertDetailId: (alertDetailId) => set({ alertDetailId }),
  setLoading: (loading) => set({ loading }),
  applyKeywordUpdate: (kw) =>
    set((state) => {
      const keywords = state.keywords.map((k) => (k.id === kw.id ? kw : k))
      return {
        keywords,
        stats: computeStats(keywords, state.alerts, state.briefs)
      }
    }),
  addAlert: (alert) =>
    set((state) => {
      const alerts = [alert, ...state.alerts]
      return {
        alerts,
        stats: computeStats(state.keywords, alerts, state.briefs)
      }
    }),
  updateAlertReadState: (id, read) =>
    set((state) => {
      const alerts = state.alerts.map((alert) =>
        alert.id === id ? { ...alert, read } : alert
      )
      return {
        alerts,
        stats: computeStats(state.keywords, alerts, state.briefs)
      }
    }),
  markAllAlertsRead: () =>
    set((state) => {
      if (!state.alerts.some((alert) => !alert.read)) return state
      const alerts = state.alerts.map((alert) => ({ ...alert, read: true }))
      return {
        alerts,
        stats: computeStats(state.keywords, alerts, state.briefs)
      }
    }),
  addTopicRun: (run) =>
    set((state) => ({
      topicRuns: [run, ...state.topicRuns.filter((item) => item.id !== run.id)].slice(0, 600)
    })),
  addBrief: (brief) =>
    set((state) => {
      const briefs = [brief, ...state.briefs.filter((item) => item.id !== brief.id)].slice(0, 50)
      return {
        briefs,
        stats: computeStats(state.keywords, state.alerts, briefs)
      }
    })
}))
